### ISSUE TITLE
getImages -- api next appears to have changed format

### ISSUE THREAD

**Issue by sumpton** [macbre/nodemw#101]
getImages()

https://github.com/macbre/nodemw/blob/devel/lib/bot.js#L757

next.aifrom is undefined, so (next && next.aifrom) is false

next appears to be an object like

{ aicontinue: '007-VARGR-Mooney.jpg', continue: '-||' }

**Comment by macbre** [comment]
@sumpton, can you provide an example URL of MW API response?
