### ISSUE TITLE
Replace jshint with eslint

### ISSUE THREAD

**Issue by zeljkofilipin** [macbre/nodemw#136]
MediaWiki core has moved from [jscs+jshint to eslint in 2016](https://phabricator.wikimedia.org/rMWc0fb8a883633f110a8083a164672e8334714d450). I volunteer to work on the transition in small commits that are easy to review. That is, if moving to eslint is something you would like to do. If not, feel free to close this issue.

**Comment by macbre** [comment]
Well, let's try it :smile:

**Comment by zeljkofilipin** [comment]
I have started working on it in #138.

**Comment by macbre** [comment]
I believe this one is done now :)
