### ISSUE TITLE
Promise sometimes rejected multiple times

### ISSUE THREAD

**Issue by bennlich** [macbre/nodemw#42]
Both of [these](https://github.com/macbre/nodemw/blob/devel/lib/api.js#L162-L179) promise rejections can happen at the same time, which throws an error in deferred.js. (Aside: I've read that in some promise implementations, the second rejection is treated as a noop.)

Not sure what the best way to solve this is. It's nice to get the info for both errors, but it's not nice for the server to crash. Maybe could test each case separately, without rejecting, then do one combined rejection after both if statements?

**Comment by macbre** [comment]
Solved by #38
