### ISSUE TITLE
Cannot read property 'result' of undefined

### ISSUE THREAD

**Issue by Fannon** [macbre/nodemw#44]
This happens if mediawiki crashes (PHP error) to nodemw: 

Maybe this is something you should check and return as an err callback instead.
Thanks for introducing this, btw!

```bash
TypeError: Cannot read property 'result' of undefined
at [...]\node_modules\nodemw\lib\bot.js:299:22
```

**Comment by Fannon** [comment]
So instead of 

```javascript
if (!err && data.result && data.result === "Success")
```

Using this should fix it:
```javascript
if (!err && data && data.result && data.result === "Success") {
```

**Comment by macbre** [comment]
Fixed the root cause in `api.js`.

Thanks for the report. Pushed `nodemw@0.4.1` to npm.
