### ISSUE TITLE
Introduce promise pattern and improve errors handling

### ISSUE THREAD

**Issue by bennlich** [macbre/nodemw#5]
What's the best way to catch api errors? For example, I want to catch "Page doesn't exist" errors when I try to delete pages that don't exist, but surrounding bot.delete() calls in a try/catch doesn't seem to work.

**Comment by MattiSG** [comment]
Why has this issue been reopened?

Also, this seems to be contradictory with another `v0.4` issue, #38.

**Comment by macbre** [comment]
@MattiSG, you're right. Let's stick to the NodeJS-style callback (#36). Closing this one.

Promise pattern can be used via 3rd-party libraries that offer "promisification" of callbacks.

**Comment by MattiSG** [comment]
:+1:
