### ISSUE TITLE
api.call -> token must be sent as POST parameter

### ISSUE THREAD

**Issue by Fannon** [macbre/nodemw#60]
Hello!

I'm using the api.call method for editing pages, because I needed to adjust some more advanced parameters. The wiki of course needs the token in order to do this, but I can't send it through the parameters:

```code="mustposttoken" info="The token parameter was found in the query
string, but must be in the POST body"```

If I don't set the token parameter I'll get `The token parameter must be set`

Best,
Simon

**Comment by macbre** [comment]
@Fannon, are you calling `this.api.call` with third argument (`method`) set to `POST`?

An example of POST API request: https://github.com/macbre/nodemw/blob/devel/lib/bot.js#L620-628

**Comment by Fannon** [comment]
Thanks, this solved my problem!
