### ISSUE TITLE
Add automatic continuation for "getPagesInCategory"?

### ISSUE THREAD

**Issue by me-12** [macbre/nodemw#65]
Do you mind adding  a automatic continuation mechanism for getPagesInCategory? Because right now, it will stop after 500 entries. Any "cmlimit" value over 500 has no effect either (due to wikimedia).

I tried something fast (without fully reading through all the code). 

This does the job for me:

I replaced:
```javascript
this.api.call({
	action: 'query',
	list: 'categorymembers',
	cmtitle: category,
	cmlimit: 5000
}, function(err, data) {
	callback(err, data && data.categorymembers || []);
});
```

with:
```javascript
this.getAll(
	{
		action: 'query',
		list: 'categorymembers',
		cmtitle: category,
		cmlimit: 5000,
		cmtype: 'page',
		rawcontinue: true
	},
	'categorymembers',
	callback
);
```

inside "getPagesInCategory".

No idea if it is complete BS though.

**Comment by macbre** [comment]
@me-12, can you provide an example of an article with over 500 categories?

**Comment by me-12** [comment]
Sure.

For example:
http://en.wikipedia.org/wiki/Category:2000_video_games
http://en.wikipedia.org/w/api.php?action=query&list=categorymembers&cmtitle=Category%3A2000_video_games&cmlimit=500&format=json

Or:
https://en.wikipedia.org/wiki/Category:Sports_cars
https://en.wikipedia.org/w/api.php?action=query&list=categorymembers&cmtitle=Category%3ASports_cars&cmlimit=500&format=json

**Comment by macbre** [comment]
@me-12 - your patch is correct. #64 will fix the issue in all places where `getAll` / pagination handling is used.
