### ISSUE TITLE
Hardcoded "Category:" prefix in .getPagesInCategory() method

### ISSUE THREAD

**Issue by pavelmn** [macbre/nodemw#77]
In non-english wiki .getPagesInCategory() doesn't work, since the prefix can vary for each wiki.

**Comment by macbre** [comment]
Can you provide an example API query / wiki URL?

I frequently run `nodemw` powered bot on a Polish wiki and did not run into any issues. MediaWiki supports both localized and canonical namespace prefixes / special page names.
