### ISSUE TITLE
Resolving redirects

### ISSUE THREAD

**Issue by guiwp** [macbre/nodemw#97]
What about more one boolean parameter in `getArticle: function(title, redirect, callback) {`?

`if (redirect) params.redirects=1`

[API:Query#Resolving_redirects](https://www.mediawiki.org/wiki/API:Query#Resolving_redirects)

**Comment by Caleb-An** [comment]
@macbre This would simplify something I'm building; would be glad to implement a pull request for this if you're not currently working on it

**Comment by macbre** [comment]
@Caleb-An, I somehow managed to miss your comment. Implemented in #106
